### ISSUE TITLE
i am run on windows xp sp3,it crashed

### ISSUE THREAD

**Issue by GaoJones** [MatthewKing/DeviceId#15]
![微信图片_20200624102009](https://user-images.githubusercontent.com/25679319/85490580-98543000-b604-11ea-9667-017b380a45bf.png)

**Comment by MatthewKing** [comment]
Hi.

Windows XP has been EOL since 2014. I don't have a Windows XP machine, nor do I have any way of attempting to reproduce this issue. Are you able to translate that error message to English please?

I'm planning to put some extra error handling in the GetMacAddressesUsingWmi method, which might help. But I don't have a timeline for the next release yet.

If none of the above help, I'd welcome a pull request.

Cheers

**Comment by GaoJones** [comment]
I recorded the stack trace info below, i am run a virtual machine(win xp sp3) 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.PropertyData.RefreshPropertyInfo()
   at System.Management.PropertyDataCollection.get_Item(String propertyName)
   at System.Management.ManagementBaseObject.GetPropertyValue(String propertyName)
   at System.Management.ManagementBaseObject.get_Item(String propertyName)
   at DeviceId.Components.NetworkAdapterDeviceIdComponent.GetMacAddressesUsingWmi()
   at DeviceId.Components.NetworkAdapterDeviceIdComponent.GetValue()
   at DeviceId.Formatters.HashDeviceIdFormatter.<>c.<GetDeviceId>b__3_1(IDeviceIdComponent x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at DeviceId.Formatters.HashDeviceIdFormatter.GetDeviceId(IEnumerable`1 components)
   at DeviceId.DeviceIdBuilder.ToString()

**Comment by MatthewKing** [comment]
Thanks. Do you have the actual error message?

**Comment by MatthewKing** [comment]
I've pushed a new commit to add some extra error handling. Can you check out the code and see if you can run it without errors? Thanks.

**Comment by GaoJones** [comment]
I've check out you lastest code and rebuild it,but it still throw exception
![微信图片_20200624122514](https://user-images.githubusercontent.com/25679319/85500276-caba5900-b615-11ea-8055-3b4917684ce9.png)

**Comment by MatthewKing** [comment]
Are you sure you've compiled against the latest code from GitHub (not on NuGet)?

**Comment by GaoJones** [comment]
yes,I am sure it is you latest code,you can install VMWare and xp stystem to try it

**Comment by MatthewKing** [comment]
That's odd. However, as mentioned before, Windows XP has been EOL since 2014 so I'm not really able to investigate this one further. If you figure it out, I'll happily accept a pull request. Cheers!
